### ISSUE TITLE
在Readme中添加tldr的链接

### ISSUE THREAD

**Issue by onesuper** [cs1707/tldr-alfred#5]
https://github.com/tldr-pages/tldr/issues/931

> We sure could (feel free to submit a PR). But I feel it would be only fair for the tldr project to be linked to from their README as well.

可以 readme 中提及 tldr 项目 ，然后给 tldr 提一个 PR，把这个项目的地址加入它们的 readme~

**Comment by cs1707** [comment]
提交pr了，Thanks～
