### ISSUE TITLE
Does not work for me

### ISSUE THREAD

**Issue by nikivdev** [cs1707/tldr-alfred#7]
I get no results : 

![](https://i.imgur.com/BE4eFLu.png)

After typing tldr and pressing space, it just quits.

**Comment by cs1707** [comment]
The workflow will clone the whole [tldr](https://github.com/tldr-pages/tldr) project at the first time.
It will take a while. Wait some minutes and try again. If it doesn't work, try to delete the folder `/Users/{{your user name}}/Library/Application Support/Alfred 3/Workflow Data/com.chedanji.tldr/` and rerun the workflow.

**Comment by nikivdev** [comment]
That also unfortunately doesn't work. I deleted the folder and rerun the workflow. Nothing happens.

**Comment by cs1707** [comment]
Would you mind provide more information. 
- your mac os version
- your alfred version
- the workflow debug info

![2016-10-31 3 01 41](https://cloud.githubusercontent.com/assets/5404420/19846715/a73560fa-9f7c-11e6-89d0-081ac463bbb9.png)

**Comment by nikivdev** [comment]
- macOS version El Captain latest 
- alfred ver 3 
- debug info 

![2016-10-31 at 21 35](https://cloud.githubusercontent.com/assets/6391776/19870770/4e23c64c-9fb2-11e6-9af4-40080436824d.png)

**Comment by cs1707** [comment]
download and install the workflow [tldr-alfred](https://raw.githubusercontent.com/cs1707/tldr-alfred/dev/tldr.alfredworkflow). if it doen't work yet, give me debug info.

**Comment by nikivdev** [comment]
What I get in debug window: 

``` Bash
Starting debug for 'tldr'

[2016-11-01 13:53:17][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "tldr.py", line 22, in query
    clone()
  File "tldr.py", line 157, in clone
    raise Exception(err)
Exception: git: error: can't exec '/Applications/Xcode.app/Contents/Developer/usr/bin/git' (errno=Permission denied)
```

**Comment by cs1707** [comment]
`brew install git` or download from [https://git-scm.com/downloads](https://git-scm.com/downloads)

**Comment by nikivdev** [comment]
But I do have git installed through home-brew already.

That's strange that it gives this error.

**Comment by cs1707** [comment]
download [tldr-alfred](https://raw.githubusercontent.com/cs1707/tldr-alfred/dev/tldr.alfredworkflow).
If it doesn't work yet , command `which git`, `where git`, give me more information.

**Comment by nikivdev** [comment]
![2016-11-02 at 10 01](https://cloud.githubusercontent.com/assets/6391776/19922550/63ea6f62-a0e3-11e6-8c08-4dc485d3fd4c.png)

**Comment by johncaijing** [comment]
![image](https://cloud.githubusercontent.com/assets/8317477/20383900/8aa7af24-acec-11e6-8492-9c0f55609953.png)

I also have this problem.

**Comment by willisworley** [comment]
I also have this problem.

**Comment by willisworley** [comment]
download   [tldr-alfred](https://raw.githubusercontent.com/cs1707/tldr-alfred/dev/tldr.alfredworkflow).
If it doesn't work yet , command which git, where git, give me more information.OK I solved it.Thank you.

**Comment by iwestlin** [comment]
@JohnTsaiAndroid 遇到同样的问题，debug显示少了个 index.json文件，路径是 `/Users/$USER/Library/Application Support/Alfred 3/Workflow Data/com.chedanji.tldr/tldr/pages/index.json`
其中内容就一行
`{"commands":[]}
`
添加后我就能用了……

**Comment by olyckne** [comment]
I also have this problem

It seems to fail on downloading the index, getting a 403 forbidden. Weird since https://tldr-pages.github.io/assets/index.json works in the browser and with curl?
```
Debug info:
[2017-11-27 10:01:32][input.scriptfilter] Queuing argument ''
[2017-11-27 10:01:33][input.scriptfilter] Script with argument '(null)' finished
[2017-11-27 10:01:33][input.scriptfilter] HTTP Error 403: Forbidden
<?xml version="1.0" ?><items><item arg="Please input" autocomplete="" uid="1" valid="no"><title>Please input</title><subtitle/><icon>icon.png</icon></item></items>
[2017-11-27 10:01:33][ERROR: input.scriptfilter] JSON error: JSON text did not start with array or object and option to allow fragments not set. in JSON:
HTTP Error 403: Forbidden
<?xml version="1.0" ?><items><item arg="Please input" autocomplete="" uid="1" valid="no"><title>Please input</title><subtitle/><icon>icon.png</icon></item></items>
[2017-11-27 10:01:34][input.scriptfilter] Queuing argument 'v'
[2017-11-27 10:01:35][input.scriptfilter] Script with argument '(null)' finished
[2017-11-27 10:01:35][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "tldr.py", line 47, in query
    rowList = parse_man_page(command)
  File "tldr.py", line 142, in parse_man_page
    page_path = find_page_location(command)
  File "tldr.py", line 64, in find_page_location
    encoding='utf-8') as f:
IOError: [Errno 2] No such file or directory: '/Users/$USER/Library/Application Support/Alfred 3/Workflow Data/com.chedanji.tldr2/index.json'
```


MacOS version 10.13.1 (17B48)
Alfred version: v3.5.1 (883)

```
$ where git
/usr/local/bin/git
/usr/local/bin/git  
/usr/local/bin/git  
/usr/bin/git
```
